name: NeutronStars
favicon: null
layout_spectrum: 0.06215427815914154
typography_spectrum: 0.6210362163837999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23694955348037183
  lightness: 0.17158951284363866
  saturation: 0.7442324438598007
  rhythmicContrast: 0.55337421502918
purpose: []
